[platformio]
default_envs = esp32-tft-128x160
src_dir = src
boards_dir = boards

[env]
platform = espressif32@6.7.0
framework = arduino
monitor_speed = 115200
upload_speed = 921600
check_tool = cppcheck
check_flags = --enable=all
extra_scripts = 
    pre:pre_build_current_year.py
    pre:patch.py
    post:patch_library_conflicts.py

[env_4mb]
extends = env
board_build.partitions = custom_4Mb_bruce.csv
build_src_filter = +<*> -<modules/gps/*>
lib_deps = 
    bodmer/TFT_eSPI @ 2.5.43
    bblanchon/ArduinoJson @ 7.1.0
    lennarthennigs/Button2 @ 2.3.2
    h278235750/LovyanGFX @ 1.1.12
build_flags = 
    -Os
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
    -DCONFIG_BT_ALLOCATION_FROM_SPIRAM_FIRST=1
    -DFLASH_4MB

[env_8mb]
extends = env
board_build.partitions = custom_8Mb.csv
build_src_filter = +<*>
lib_deps = 
    bodmer/TFT_eSPI @ 2.5.43
    bblanchon/ArduinoJson @ 7.1.0
    lennarthennigs/Button2 @ 2.3.2
    h278235750/LovyanGFX @ 1.1.12
build_flags = 
    -Os
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
    -DFLASH_8MB

[env_16mb]
extends = env
board_build.partitions = custom_16Mb.csv
build_src_filter = +<*>
lib_deps = 
    bodmer/TFT_eSPI @ 2.5.43
    bblanchon/ArduinoJson @ 7.1.0
    lennarthennigs/Button2 @ 2.3.2
    h278235750/LovyanGFX @ 1.1.12
build_flags = 
    -Os
    -DCORE_DEBUG_LEVEL=0
    -DCONFIG_ARDUINO_LOOP_STACK_SIZE=16384
    -DFLASH_16MB

; ==========================================
; CUSTOM BUILD FOR 1.8" TFT ST7735 & BUTTONS
; ==========================================
[env:esp32-tft-128x160]
extends = env_4mb
board = esp32dev
board_build.partitions = custom_4Mb_bruce.csv
build_src_filter = ${env_4mb.build_src_filter}

build_flags =
  ${env_4mb.build_flags}
  -DEEPROMSIZE=128
  -DLH=8
  -DLW=6
  -DESP32_TFT_128X160
  -DDEVICE_NAME='"ESP32 Custom ST7735"'
  
  ; Display Configuration Matrix
  -DHAS_SCREEN=1
  -DROTATION=1
  -DUSER_SETUP_LOADED=1
  -DST7735_DRIVER=1
  -DST7735_GREENTAB=1
  -DTFT_WIDTH=128
  -DTFT_HEIGHT=160

  ; Hardware SPI Pin Assignments
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_CS=5
  -DTFT_DC=16
  -DTFT_RST=17
  -DTFT_BL=-1

  ; Hardware Button Interface Pins
  -DSEL_BTN=25
  -DUP_BTN=33
  -DDW_BTN=27
  -DBTN_ALIAS='"OK"'
