[env:esp32-tft-128x160]
extends = env_4mb
board = esp32dev
board_build.partitions = custom_4Mb_bruce.csv
build_src_filter = ${env.build_src_filter}

build_flags =
  ${env_4mb.build_flags}
  -DEEPROMSIZE=128
  -DLH=8
  -DLW=6
  -DESP32_TFT_128X160
  -DDEVICE_NAME='"ESP32 Custom ST7735"'

  ; Display Configuration
  -DHAS_SCREEN=1
  -DROTATION=1
  -DUSER_SETUP_LOADED=1
  -DST7735_DRIVER=1
  -DST7735_GREENTAB=1
  -DTFT_WIDTH=128
  -DTFT_HEIGHT=160

  ; Display SPI Pins
  -DTFT_MOSI=23
  -DTFT_SCLK=18
  -DTFT_CS=5
  -DTFT_DC=16
  -DTFT_RST=17
  -DTFT_BL=-1

  ; Navigation Button Pins
  -DSEL_BTN=25
  -DUP_BTN=33
  -DDW_BTN=27
  -DBTN_ALIAS='"OK"'

lib_deps =
  ${env_4mb.lib_deps}
